name: Deployment-Digitec-Scrapy-Main
on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  build-with-docker:
    name: Build multi-platform Docker image
    runs-on: ubuntu-20.04

    steps:
      - name: Generate changelog
        id: changelog
        uses: ./
        with:
          create-summary: true

      - name: Create Release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lukzimmermann/digitec_scrapy_client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
